default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch('RAILS_MAX_THREADS') { 5 } %>
  port: 5432
  username: <%= ENV['SLINGS_DATABASE_USERNAME'] %>
  password: <%= ENV['SLINGS_DATABASE_PASSWORD'] %>

development:
  <<: *default
  database: slings_development

test:
  <<: *default
  database: slings_test

production:
  <<: *default
  database: slings_production
